import Head from 'next/head'
import Character from '../components/Character.js';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Kanit:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,900;1,100&family=Manrope:wght@200;300;400;500;700;800&family=Roboto+Mono:wght@400;700&family=Silkscreen&display=swap" rel="stylesheet"></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Character/>
      </main>
      <footer>
      </footer>
    </div>
  )
}
